<script setup></script>

<template>
  <h2 class="text-h2 mb-12">Buttons</h2>
  <div class="d-flex mb-4">
    <v-btn
      class="mx-2"
      color="primary"
      >Primary</v-btn
    >
    <v-btn
      class="mx-2"
      color="secondary"
      >Secondary</v-btn
    >
    <v-btn
      class="mx-2"
      color="tertiary"
      >Tertiary</v-btn
    >
    <v-btn
      class="mx-2"
      color="quaternary"
      >Quaternary</v-btn
    >
    <v-btn
      class="mx-2"
      color="warning"
      >Warning</v-btn
    >
    <v-btn
      class="mx-2"
      color="info"
      >Info</v-btn
    >
    <v-btn
      class="mx-2"
      color="error"
      >Error</v-btn
    >
  </div>
  <div class="d-flex mb-4">
    <v-btn
      class="mx-2"
      variant="outlined"
      color="primary"
      >Primary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="outlined"
      color="secondary"
      >Secondary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="outlined"
      color="tertiary"
      >Tertiary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="outlined"
      color="quaternary"
      >Quaternary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="outlined"
      color="warning"
      >Warning</v-btn
    >
    <v-btn
      class="mx-2"
      variant="outlined"
      color="info"
      >Info</v-btn
    >
    <v-btn
      class="mx-2"
      variant="outlined"
      color="error"
      >Error</v-btn
    >
  </div>
  <div class="d-flex mb-4">
    <v-btn
      class="mx-2"
      variant="tonal"
      color="primary"
      >Primary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="tonal"
      color="secondary"
      >Secondary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="tonal"
      color="tertiary"
      >Tertiary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="tonal"
      color="quaternary"
      >Quaternary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="tonal"
      color="warning"
      >Warning</v-btn
    >
    <v-btn
      class="mx-2"
      variant="tonal"
      color="info"
      >Info</v-btn
    >
    <v-btn
      class="mx-2"
      variant="tonal"
      color="error"
      >Error</v-btn
    >
  </div>
  <div class="d-flex mb-4">
    <v-btn
      class="mx-2"
      variant="text"
      color="primary"
      >Primary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="text"
      color="secondary"
      >Secondary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="text"
      color="tertiary"
      >Tertiary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="text"
      color="quaternary"
      >Quaternary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="text"
      color="warning"
      >Warning</v-btn
    >
    <v-btn
      class="mx-2"
      variant="text"
      color="info"
      >Info</v-btn
    >
    <v-btn
      class="mx-2"
      variant="text"
      color="error"
      >Error</v-btn
    >
  </div>
  <div class="d-flex mb-4">
    <v-btn
      class="mx-2"
      variant="plain"
      color="primary"
      >Primary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="plain"
      color="secondary"
      >Secondary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="plain"
      color="tertiary"
      >Tertiary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="plain"
      color="quaternary"
      >Quaternary</v-btn
    >
    <v-btn
      class="mx-2"
      variant="plain"
      color="warning"
      >Warning</v-btn
    >
    <v-btn
      class="mx-2"
      variant="plain"
      color="info"
      >Info</v-btn
    >
    <v-btn
      class="mx-2"
      variant="plain"
      color="error"
      >Error</v-btn
    >
  </div>
  <div class="d-flex mb-4">
    <v-btn
      class="mx-2"
      disabled
      color="primary"
      >Primary</v-btn
    >
    <v-btn
      class="mx-2"
      disabled
      color="secondary"
      >Secondary</v-btn
    >
    <v-btn
      class="mx-2"
      disabled
      color="tertiary"
      >Tertiary</v-btn
    >
    <v-btn
      class="mx-2"
      disabled
      color="quaternary"
      >Quaternary</v-btn
    >
    <v-btn
      class="mx-2"
      disabled
      color="warning"
      >Warning</v-btn
    >
    <v-btn
      class="mx-2"
      disabled
      color="info"
      >Info</v-btn
    >
    <v-btn
      class="mx-2"
      disabled
      color="error"
      >Error</v-btn
    >
  </div>
</template>
