name: Blackduck Scan

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: "Branch that should be scanned"
        default: "main"
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      version:
        type: string
        required: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ☁ Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: ⬇ Install npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: 🤞 Synopsys Detect
        uses: blackducksoftware/github-action@v2
        with: 
          args: 
            '--blackduck.url="https://bdscan.daimler.com" --blackduck.api.token="${{ secrets.BD_SCAN_API_TOKEN }}" --detect.policy.check.fail.on.severities="MAJOR,CRITICAL,BLOCKER" --detect.npm.include.dev.dependencies=true --detect.project.name="product-kit-vue" --detect.project.version.name="${{ github.event.inputs.version }}" --detect.project.version.phase=RELEASED --detect.notices.report=true --detect.notices.report.path="./notices"'
      - name: 🔀 Rename notices
        run: for f in ./notices/product_kit_vue*.txt; do mv "$f" 3RD_PARTY_LICENSES.txt; done
      - name: ☁ Commit Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: bd-scan automated script
          author_email: ci@automate.bot
          message: "Updated 3rd party licenses file to version ${{ github.event.inputs.version }}"
          add: "3RD_PARTY_LICENSES.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
