name: Blackduck Scan

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: "Branch that should be scanned"
        default: "main"
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'
      projectname:
        description: 'BD project name'
        required: true
        default: 'product-kit-vue'
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      version:
        type: string
        required: true


jobs:
  scan:
    uses: mercedes-benz/product-kit_core/.github/workflows/bd-scan.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
      projectname: ${{ github.event.inputs.projectname }}
      
