name: Blackduck Scan

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: "Branch that should be scanned"
        default: "main"
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      version:
        type: string
        required: true

jobs:
  scan:
    uses: mercedes-benz/product-kit_core/.github/workflows/bd-scan.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
    secrets:
      projectname: ${{ secrets.BD_SCAN_PROJECT_NAME }}
      BLACKDUCK_API_TOKEN: ${{ secrets.BD_SCAN_API_TOKEN }}
      
