name: Pre Release Checks

on:
  pull_request:
    branches:
      - develop

jobs:
  run-checks:
    uses: michaelgeyer/github-actions-test/.github/workflows/pre-release-checks.yml@main
    with:
      npm-package-url: https://unpkg.com/@daimler/productkit-vue/package.json
      black-duck-project-name: product-kit-vue